INSERT INTO ROLES(ID, NAME) VALUES(1,'ADMIN');

INSERT INTO ROLES(ID, NAME) VALUES(2,'CUSTOMER');

INSERT INTO CATEGORIES(ID, NAME, CREATION_DATE) VALUES(NEXT VALUE FOR primary_sequence_cat, 'Food',NOW());
INSERT INTO CATEGORIES(ID, NAME, CREATION_DATE) VALUES(NEXT VALUE FOR primary_sequence_cat, 'Tech',NOW());
INSERT INTO CATEGORIES(ID, NAME, CREATION_DATE) VALUES(NEXT VALUE FOR primary_sequence_cat, 'Skin Care',NOW());
INSERT INTO CATEGORIES(ID, NAME, CREATION_DATE) VALUES(NEXT VALUE FOR primary_sequence_cat, 'Bath',NOW());
