CREATE SEQUENCE primary_sequence_rol START WITH 1 INCREMENT BY 1;
CREATE TABLE ROLES(
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE primary_sequence_usr START WITH 1 INCREMENT BY 1;
CREATE TABLE USERS(
    ID INT NOT NULL PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL,
    U_PASSWORD VARCHAR2(100) NOT NULL,
    ROLE_ID INT NOT NULL,
    FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ID)
);

CREATE SEQUENCE primary_sequence_ord START WITH 1 INCREMENT BY 1;
CREATE TABLE ORDERS(
    ID INT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR2(1) NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE primary_sequence_prod START WITH 1 INCREMENT BY 1;
CREATE TABLE PRODUCTS(
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(500)
);

CREATE SEQUENCE primary_sequence_prod_ord START WITH 1 INCREMENT BY 1;
CREATE TABLE PRODUCT_ORDERS(
    ID INT NOT NULL PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE SEQUENCE primary_sequence_pay START WITH 1 INCREMENT BY 1;
CREATE TABLE PAYMENTS(
    ID INT NOT NULL PRIMARY KEY,
    TOTAL NUMERIC NOT NULL,
    PAYMENT_STATUS VARCHAR2(1) NOT NULL,
    PAYMENT_DATE DATE,
    ORDER_ID INT NOT NULL,
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID)
);

CREATE SEQUENCE primary_sequence_cat START WITH 1 INCREMENT BY 1;
CREATE TABLE CATEGORIES(
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CREATION_DATE DATE NOT NULL
);